name: test

on:
  pull_request:
    paths:
      - 'src/**'

jobs:
  test-setup:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: run install script
      run: echo "" | ./src/install-outlook-sync.sh
    
